# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/dvi2rgb_0.xci
# IP: The module: 'dvi2rgb_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_refclk/ila_refclk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] -quiet

# IP: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_pixclk/ila_pixclk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_refclk/ila_refclk_ooc.xdc

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_timing_workaround.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_pixclk/ila_pixclk_ooc.xdc

# IP: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/dvi2rgb_0.xci
# IP: The module: 'dvi2rgb_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_refclk/ila_refclk.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] -quiet

# IP: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_pixclk/ila_pixclk.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_refclk || ORIG_REF_NAME==ila_refclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_refclk/ila_refclk_ooc.xdc

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_timing_workaround.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dvi2rgb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_pixclk || ORIG_REF_NAME==ila_pixclk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jawah/hdmi_2_vga/hdmi_2_vga.srcs/sources_1/ip/dvi2rgb_0/src/ila_pixclk/ila_pixclk_ooc.xdc
